### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by wildmaster84** [Ferks-FK/Pterodactyl-Docker#1]
When running the bash command, it returns this.
![image](https://user-images.githubusercontent.com/46942741/158042745-ae566f06-1fb7-4a59-8e10-c3337929893f.png)

When i use curl to run the script, it says command not found>
![image](https://user-images.githubusercontent.com/46942741/158042764-7614b509-6ef3-4d61-92e7-1fbbfc7dd635.png)

**Comment by Ferks-FK** [comment]
You should not run the help script manually.
You need to run the main script.
